services:
  mongo:
    image: mongo:6.0
    container_name: chatapp-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7.2
    container_name: chatapp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  redis_data:
